language: php

matrix:
  include:
    - php: 5.3
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - SEND_COVERAGE=true
    - php: 7
    - php: hhvm 
                    
before_script:
  - sudo apt-get install --yes ant
  - travis_retry composer self-update
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot
  - mysql -e "create database phpunit_soluble_test_db;" -uroot
  - zcat test/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db
  - zcat test/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db
  - mkdir build
  - mkdir -p build/logs
  - mkdir -p test/logs
  
script: 
  - phpunit -v 

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.xml; fi
  #- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then coveralls ; fi